meta:
  description: Naemon plugin to verify ssh connectivity within an OP5 Monitor cluster.
  vendor: ITRS Group
  maintainer: Johan Thorén <jthoren@itrsgroup.com>
  license: GPLv3
files:
  "/opt/plugins/check_monitor_ssh":
    file: check_monitor_ssh-linux-x86_64
    mode: "0755"
    user: "root"
  "/usr/share/doc/check_monitor_ssh/README.md":
    file: README.md
    mode: "0644"
    user: "root"
  "/usr/share/licenses/check_monitor_ssh/LICENSE":
    file: LICENSE
    mode: "0644"
    user: "root"
