meta:
  description: Naemon plugin to verify ssh connectivity within an OP5 Monitor cluster.
  vendor: ITRS Group
  maintainer: Johan Thorén <jthoren@itrsgroup.com>
files:
  "/opt/plugins/check_monitor_ssh":
    file: check_monitor_ssh-linux-x86_64
    mode: "0755"
    user: "root"
