#!/usr/bin/env bash
REMOTE="$1"
BIN_NAME="check_monitor_ssh"

perform_task() {
    sh -c "$1" || exit 1
}

tasks=("lein test"
       "lein clean"
       "lein uberjar"
       "find target -name '*standalone.jar' -exec scp {} ${REMOTE}:${BIN_NAME}/target/ \;"
       "ssh -t ${REMOTE} 'cd ${BIN_NAME} && lein native'"
       "scp ${REMOTE}:${BIN_NAME}/target/${BIN_NAME} ~/Downloads/"
)

for task in "${tasks[@]}"; do
    perform_task "$task"
done
