name: Build and publish a check_monitor_ssh release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Make and upload binary as release asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build statically linked binary
        run: make
      - name: Compress binary
        working-directory: ./target
        run: tar cvzf linux-amd64-statically-linked-check_monitor_ssh.tar.gz check_monitor_ssh
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/linux-amd64-statically-linked-check_monitor_ssh.tar.gz
          asset_name: linux-amd64-statically-linked-check_monitor_ssh.tar.gz
          asset_content_type: application/gzip
