name: Test Suite

on:
  - push
  - pull_request

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: DeLaGuardo/setup-clj-kondo@master
        with:
          version: '2021.08.06'

      - uses: actions/checkout@v2

      - name: clj-kondo
        run: clj-kondo --lint src

      - name: Install lein deps
        run: lein deps

      - name: Lein Kibit
        run: lein kibit

  lein_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test

  build_linux:
    name: Build Linux

    needs:
      - lint
      - lein_test

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        target:
          - linux-x86_64

    steps:
      - uses: actions/checkout@v2

      - name: Make
        run: make

      - name: Move and rename binary
        run: mv target/check_monitor_ssh check_monitor_ssh-${{ matrix.target }}

      - name: Print the current state of the directory
        run: ls -alh

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: check_monitor_ssh-${{ matrix.target }}
          path: check_monitor_ssh-${{ matrix.target }}

  integration_tests:
    name: Run integration tests

    needs:
      - lint
      - lein_test
      - build_linux

    runs-on: ${{ matrix.os }}

    env:
      BATS_DIR: "test/check_monitor_ssh/bats/"
      BATS_EXT_URL: "https://raw.githubusercontent.com/mbland/go-script-bash/master/lib/bats"

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        include:
          - os: ubuntu-latest
            target: linux-x86_64

    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.4.1

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create directory for bats extensions
        run: mkdir -p "$BATS_DIR"

      - name: Download bats extensions
        run: |
          curl ${BATS_EXT_URL}/assertion-test-helpers -o ${BATS_DIR}
          curl ${BATS_EXT_URL}/assertions -o ${BATS_DIR}
          curl ${BATS_EXT_URL}/background-process -o ${BATS_DIR}
          curl ${BATS_EXT_URL}/helper-function -o ${BATS_DIR}
          curl ${BATS_EXT_URL}/helpers -o ${BATS_DIR}

      - name: Display the contents of the test dir
        run: ls -Ral test

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: check_monitor_ssh-${{ matrix.target }}

      - name: Make artifact executable
        run: chmod +x check_monitor_ssh-${{ matrix.target }}

      - name: List directory
        run: ls -alh

      - name: Rename binary
        run: mv check_monitor_ssh-${{ matrix.target }} check_monitor_ssh

      - name: Run tests
        shell: bash
        run: bats -r .
